### ISSUE TITLE
Password Reset flow till entering the OTP

### ISSUE THREAD

**Issue by Airace99** [brightcone/bart#7]
according to [Figma](https://www.figma.com/proto/PY16GuwiHSIZhA1ASGUpG6/Presentation?page-id=762%3A9630&node-id=795-15533&viewport=928%2C458%2C0.17&t=xVkoYYng3ydmMbh5-1&scaling=contain&content-scaling=fixed),

we have to develop the functionality till the point where we enter the OTP

**Comment by aneesh-bukya** [comment]
Password Reset Functionality

This feature allows users to seamlessly reset their passwords across various services through an interactive chatbot interface. Below is a detailed breakdown of the process:

1. **Password Reset Request:**  
   Users initiate the password reset process by requesting assistance from the chatbot.

2. **Service Selection:**  
   The chatbot prompts the user to select the specific service for which they wish to reset the password. Available options may include services such as the Employee Portal, Email, etc.

3. **User Identification:**  
   The chatbot requests the user to provide either their username or email address associated with the selected service.

4. **User Input:**  
   The user enters their username or email address, which is then verified by the system.

5. **OTP Generation and Delivery:**  
   Upon successful verification, the chatbot generates a One-Time Password (OTP) and sends it to the user's registered email address. This OTP is required to complete the password reset process.

**Comment by PBSquare** [comment]
Completed on 02/08/2024
